frr defaults traditional
hostname r1
ipv6 forwarding
!
vrf RED
exit-vrf
!
interface eth1
 description to_r3_eth3
 ipv6 address 2001:c0de:1:5::1/64
 ipv6 router isis 1
 isis circuit-type level-2-only
 isis network point-to-point
exit
!
interface eth2
 description to_r4_eth3
 ipv6 address 2001:c0de:1:6::1/64
 ipv6 router isis 1
 isis circuit-type level-2-only
 isis metric level-1 10
 isis metric level-2 20
 isis network point-to-point
exit
!
interface eth3
 description to_c1_eth1
exit
!
interface eth3.10
 description to_c1_eth1.10_VRF_RED
 ip address 10.10.1.1/30
exit
!
interface lo
 description routerID
 ip address 1.1.1.1/32
 ipv6 address 2001:c0de:2::1/128
 ipv6 router isis 1
exit
!
router isis 1
 is-type level-2-only
 net 49.0001.0000.0000.0001.00
exit
!
end
