frr defaults traditional
hostname rrv6
log syslog
log file /etc/frr/logs/rrv6.log
log record-priority
log timestamp precision 3
no log unique-id
ipv6 forwarding
!
debug bgp neighbor-events
debug bgp updates in
debug bgp updates out
debug isis route-events
!
route-map PERMIT_ALL permit 10
exit
!
interface eth1
 description to_p2_eth4
 ipv6 address 2001:c0de:1:9::2/64
 ipv6 router isis 1
 isis hello padding during-adjacency-formation
 isis network point-to-point
exit
!
interface lo
 description routerID
 ip address 9.9.9.9/32
 ipv6 address fcdd:dd00:0109::1/128
 ipv6 router isis 1
 isis passive
exit
!
router bgp 65000
 bgp router-id 9.9.9.9
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 bgp cluster-id 9.9.9.9
 neighbor RRV6 peer-group
 neighbor RRV6 remote-as internal
 neighbor RRV6 update-source fcdd:dd00:0109::1
 neighbor RRV6 capability extended-nexthop
 neighbor fcdd:dd00:0101::1 peer-group RRV6
 neighbor fcdd:dd00:0102::1 peer-group RRV6
 !
 address-family ipv4 vpn
  neighbor RRV6 activate
  neighbor RRV6 route-reflector-client
 exit-address-family
exit
!
router isis 1
 is-type level-2-only
 net 49.0001.9999.9999.9999.00
exit
!
end