frr defaults traditional
hostname rrv6
log syslog
log file /etc/frr/logs/rrv6.log
log record-priority
log timestamp precision 3
no log unique-id
ipv6 forwarding
!
debug bgp neighbor-events
debug bgp updates in
debug bgp updates out
debug isis route-events
!
route-map PERMIT_ALL permit 10
exit
!
interface eth1
 description to_p2_eth4
 ipv6 address 2001:c0de:1:9::2/64
 ipv6 router isis 1
 isis hello padding during-adjacency-formation
 isis network point-to-point
exit
!
interface lo
 ipv6 address 2001:face::8/128
 ipv6 router isis 1
 isis passive
exit
!
router bgp 65000
 bgp router-id 172.16.0.8
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 bgp cluster-id 172.16.0.8
 neighbor RRV6 peer-group
 neighbor RRV6 remote-as internal
 neighbor RRV6 update-source 2001:face::8
 neighbor RRV6 capability extended-nexthop
 neighbor 2001:face::1 peer-group RRV6
 neighbor 2001:face::1 description pe1
 neighbor 2001:face::6 peer-group RRV6
 neighbor 2001:face::6 description pe2
 neighbor 2001:face::15 peer-group RRV6
 neighbor 2001:face::15 description bdr1
 !
 address-family ipv4 vpn
  neighbor RRV6 activate
  neighbor RRV6 route-reflector-client
 exit-address-family
 !
 address-family ipv6 vpn
  neighbor RRV6 activate
  neighbor RRV6 route-reflector-client
 exit-address-family
 !
 address-family ipv4 unicast
  neighbor RRV6 activate
  neighbor RRV6 route-reflector-client
 exit-address-family
exit
!
router isis 1
 is-type level-2-only
 net 49.0001.1721.6000.0008.00
exit
!
end
