frr defaults traditional
hostname p2
log syslog
log file /etc/frr/logs/p2.log
log record-priority
log timestamp precision 3
no log unique-id
!
debug zebra srv6
debug isis sr-events
debug isis route-events
debug mpls ldp events
!
interface eth1
 description to_p1_eth2
 ip address 172.16.10.3/31
 ip router isis 1
 isis hello padding during-adjacency-formation
 isis network point-to-point
exit
!
interface eth2
 description RESERVED: to_pe2_eth2
exit
!
interface eth3
 description to_p4_eth1
 ip address 172.16.10.10/31
 ip router isis 1
 isis hello padding during-adjacency-formation
 isis network point-to-point
exit
!
interface eth4
 description to_rrv4_eth2
 ip address 172.16.10.8/31
 ip router isis 1
 isis hello padding during-adjacency-formation
 isis network point-to-point
exit
!
interface lo
 description routerID
 ip address 4.4.4.4/32
 ip router isis 1
 isis passive
exit
!
mpls ldp
 router-id 4.4.4.4
 !
 address-family ipv4
  discovery transport-address 4.4.4.4
  !
  interface eth1
  exit
  !
  interface eth3
  exit
  !
  interface eth4
  exit
 exit-address-family
 !
exit
!
router isis 1
 is-type level-2-only
 net 49.0001.4444.4444.4444.00
exit
!
end