frr defaults traditional
hostname pe1
log syslog
log file /etc/frr/logs/pe1.log
log record-priority
log timestamp precision 3
no log unique-id
ipv6 forwarding
!
debug zebra srv6
debug bgp neighbor-events
debug bgp updates in
debug bgp updates out
debug isis sr-events
debug isis route-events
debug mpls ldp events
!
route-map PERMIT_ALL permit 10
exit
!
route-map LP-50 permit 10
 set local-preference 50
exit
!
vrf RED
exit-vrf
!
interface eth1
 description to_p1_eth1
 ip address 172.16.10.0/31
 ip router isis 1
 ipv6 address 2001:c0de:1:1::1/64
 ipv6 router isis 1
 isis hello padding during-adjacency-formation
 isis network point-to-point
exit
!
interface eth2
 description RESERVED: to_p3_eth2
exit
!
interface eth3
 description to_c1_eth1
exit
!
interface eth3.10 vrf RED
 description to_c1_eth1.10_VRF_RED
 ip address 10.10.1.1/30
exit
!
interface lo
 description routerID
 ip address 1.1.1.1/32
 ip router isis 1
 ipv6 address fcdd:dd00:0101::1/128
 ipv6 router isis 1
 isis passive
exit
!
router bgp 65000
 bgp router-id 1.1.1.1
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 neighbor RRV4 peer-group
 neighbor RRV4 remote-as internal
 neighbor RRV4 update-source 1.1.1.1
 neighbor RRV6 peer-group
 neighbor RRV6 remote-as internal
 neighbor RRV6 update-source fcdd:dd00:0101::1
 neighbor RRV6 capability extended-nexthop
 neighbor 8.8.8.8 peer-group RRV4
 neighbor fcdd:dd00:0109::1 peer-group RRV6
 !
 address-family ipv4 vpn
  neighbor RRV4 activate
  neighbor RRV4 next-hop-self
  neighbor RRV6 activate
  neighbor RRV6 next-hop-self
  neighbor RRV6 encapsulation-srv6
  neighbor RRV6 route-map LP-50 in
 exit-address-family
exit
!
router bgp 65000 vrf RED
 bgp router-id 1.1.1.1
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 !
 segment-routing srv6
  locator Loc0
  no srv6-only
 exit
 !
 address-family ipv4 unicast
  redistribute connected
  label vpn export auto
  sid vpn export auto
  rd vpn export 1.1.1.1:10
  rt vpn both 65000:10
  export vpn
  import vpn
 exit-address-family
exit
!
mpls ldp
 router-id 1.1.1.1
 !
 address-family ipv4
  discovery transport-address 1.1.1.1
  !
  interface eth1
  exit
  !
 exit-address-family
 !
exit
!
router isis 1
 is-type level-2-only
 net 49.0001.1111.1111.1111.00
 segment-routing srv6
  locator Loc0
 exit
exit
!
segment-routing
 srv6
  encapsulation
   source-address fcdd:dd00:0101::1
  locators
   locator Loc0
    prefix fcdd:dd00:0101::/48
    behavior usid
    format usid-f3216
   exit
   !
  exit
  !
 exit
 !
exit
!
end