frr defaults traditional
hostname r2
ip forwarding
ipv6 forwarding
!
vrf RED
exit-vrf
!
interface eth1
 description to_r5_eth3
 ipv6 address 2001:c0de:1:7::1/64
 ipv6 router isis 1
 isis hello padding during-adjacency-formation
 isis network point-to-point
exit
!
interface eth2
 description to_r6_eth3
 ipv6 address 2001:c0de:1:8::1/64
 ipv6 router isis 1
 isis metric level-1 10
 isis metric level-2 20
 isis hello padding during-adjacency-formation
 isis network point-to-point
exit
!
interface eth3
 description to_c2_eth1
exit
!
interface eth3.10
 description to_c2_eth1.10_VRF_RED
 ip address 10.10.2.1/30
exit
!
interface lo
 description routerID
 ip address 2.2.2.2/32
 ipv6 address 2001:c0de:2::2/128
 ipv6 address 2001:db8:2::1/128
 ipv6 router isis 1
 isis passive
exit
!
segment-routing
 srv6
  encapsulation
   source-address 2001:db8:2::1
  locators
   locator MAIN
    prefix 2001:db8:2::/48 block-len 32 node-len 16 func-bits 16
    behavior usid
    format usid-f3216
   exit
   !
  exit
  !
  formats
   format usid-f3216
   exit
   !
   format uncompressed-f4024
   exit
   !
  exit
  !
 exit
 !
exit
!
router bgp 65000
 bgp router-id 2.2.2.2
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 neighbor PE peer-group
 neighbor PE remote-as internal
 neighbor PE update-source 2001:c0de:2::2
 neighbor PE capability extended-nexthop
 neighbor 2001:c0de:2::1 peer-group PE
 !
 segment-routing srv6
  locator MAIN
 exit
 !
 address-family ipv4 vpn
  neighbor PE activate
  neighbor PE next-hop-self
 exit-address-family
exit
!
router bgp 65000 vrf RED
 bgp router-id 2.2.2.2
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 sid vpn per-vrf export auto
 !
 address-family ipv4 unicast
  redistribute connected
  rd vpn export 2.2.2.2:10
  rt vpn both 65000:10
  export vpn
  import vpn
 exit-address-family
exit
!
router isis 1
 net 49.0001.0000.0000.0002.00
 is-type level-2-only
 metric-style wide
 segment-routing srv6
  locator MAIN
exit
!
end
