frr defaults traditional
hostname r2
ipv6 forwarding
!
interface eth1
 description to_r5_eth3
 ipv6 address 2001:c0de:1:7::1/64
 ipv6 router isis 1
 isis circuit-type level-2-only
 isis network point-to-point
exit
!
interface eth2
 description to_r6_eth3
 ipv6 address 2001:c0de:1:8::1/64
 ipv6 router isis 1
 isis circuit-type level-2-only
 isis metric level-1 10
 isis metric level-2 20
 isis network point-to-point
exit
!
interface eth3
 description to_c2_eth1
exit
!
interface eth3.10
 description to_c2_eth1_service1
 ip address 10.10.2.1/30
exit
!
interface lo
 description routerID
 ip address 2.2.2.2/32
 ipv6 address 2001:c0de:2::2/128
 ipv6 router isis 1
exit
!
router isis 1
 is-type level-2-only
 net 49.0001.0000.0000.0002.00
exit
!
end
