frr defaults traditional
hostname p3
log syslog
log file /etc/frr/logs/p3.log
log record-priority
log timestamp precision 3
no log unique-id
!
debug zebra srv6
debug isis sr-events
debug isis route-events
debug mpls ldp events
!
interface eth1
 description to_p1_eth3
 ip address 172.16.10.5/31
 ip router isis 1
 isis hello padding during-adjacency-formation
 isis network point-to-point
 isis metric level-2 20
exit
!
interface eth2
 description RESERVED: to_pe1_eth2
exit
!
interface eth3
 description to_p4_eth2
 ip address 172.16.10.12/31
 ip router isis 1
 isis hello padding during-adjacency-formation
 isis network point-to-point
exit
!
interface eth4
 description RESERVED: to_rrv6_eth1
exit
!
interface lo
 description routerID
 ip address 5.5.5.5/32
 ip router isis 1
 isis passive
exit
!
mpls ldp
 router-id 5.5.5.5
 !
 address-family ipv4
  discovery transport-address 5.5.5.5
  !
  interface eth1
  exit
  !
  interface eth3
  exit
 exit-address-family
 !
exit
!
router isis 1
 is-type level-2-only
 net 49.0001.5555.5555.5555.00
exit
!
end