frr defaults traditional
hostname p4
log syslog
log file /etc/frr/logs/p4.log
log record-priority
log timestamp precision 3
no log unique-id
ipv6 forwarding
!
debug isis route-events
!
interface eth1
 description to_p2_eth3
 ipv6 address 2001:c0de:1:5::2/64
 ipv6 router isis 1
 isis hello padding during-adjacency-formation
 isis network point-to-point
exit
!
interface eth2
 description to_p3_eth3
 ipv6 address 2001:c0de:1:7::2/64
 ipv6 router isis 1
 isis hello padding during-adjacency-formation
 isis network point-to-point
exit
!
interface eth3
 description to_pe2_eth1
 ipv6 address 2001:c0de:1:8::1/64
 ipv6 router isis 1
 isis hello padding during-adjacency-formation
 isis network point-to-point
exit
!
interface lo
 description routerID
 ip address 172.16.0.5/32
 ipv6 address fcdd:dd00:0105::1/128
 ipv6 router isis 1
 isis passive
exit
!
router isis 1
 is-type level-2-only
 net 49.0001.1721.6000.0005.00
exit
!
end
